# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyRX' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
end

target 'CurrencyRXTests' do
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
end
