# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyRX' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
  

  target 'CurrencyRXTests' do
    inherit! :search_paths
    pod 'RxBlocking'
    pod 'RxTest'

  end
end

 